---
title       : MPG Prediction
subtitle    : With Mtcars Data
author      : Yining Qi
job         : Student
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Why predict?

MPG is the abbreviation of miles per (US) gallon, which is the indicator of the fuel consumption of the cars. 
### Why do you need the MPG value?
1. Saving money.
2. For Better environment.

--- .class #id

## Dataset from R Package: mtcars

```mtcars``` is a classical dataset provided in the R package {datasets}. It contains data of different kinds of cars and we can train a model with the data conveniently. Particularly, in mtcars, "wt" means weight, and "am" means transmission(auto-matic/manual), which are the two main predictors in the model.
```{r,echo=FALSE}
library(datasets)
data(mtcars)
str(mtcars)
```

--- .class #id

## Building the Model

### Method: Random Forest

We choose the method of random forest to build the predicting model.

Random forests are an ensemble learning method for classification, regression and other tasks, that operate by constructing a multitude of decision trees at training time and outputting the class that is the mode of the classes (classification) or mean prediction (regression) of the individual trees. 

Random forests correct for decision trees' habit of overfitting to their training set.(From [Random forest-Wiki](https://en.wikipedia.org/wiki/Random_forest))

### Model: Interaction between weight and transmission

We train the model, considering that there is interaction between weight and transmission. 

--- .class #id

## Using the App

We provide prediction with weight ranging from 1.5 klbs to 5.5 klbs, and an option to decide whether the car is manual or not. 

You may find that some prediction values have minor differences with original ones. That is because the impact of noise. But we consider that the differences are not very big that they can be acceptable.

--- .class #id